# **Notebook 3: Modelling**

In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sb
import warnings as warnings

In [41]:
dataset=pd.read_csv('/Users/mussabasif/WildfirePrediction/Wildfire-Prediction-Classification/data/processed/df_processed.csv')

In [42]:
dataset

         temp    rh    ws  precip  rndays  fwi  calcstatus risk_band
0         9.5  94.0   8.6   20.52       0  0.0           1  moderate
1         1.0  86.7  11.1    1.71       0  0.0           1  moderate
2        -2.0  74.4   0.0    0.00       1  0.0           1  moderate
3        13.2  97.0   3.7   16.80       0  0.0           1  moderate
4         2.0  93.2  13.0    3.80       0  0.0           1  moderate
...       ...   ...   ...     ...     ...  ...         ...       ...
3162082 -13.6  65.0  18.4    1.90       0  NaN          -3   no_risk
3162083 -23.0  59.0  25.8    3.37       0  NaN          -3   no_risk
3162084 -23.1  61.0  25.8    3.37       0  NaN          -3   no_risk
3162085 -30.9  59.0  20.5    0.00      15  NaN          -3   no_risk
3162086 -13.4  39.0  29.6    0.00       7  NaN          -3   no_risk

[3162087 rows x 8 columns]

In [43]:
X, y=dataset[['temp', 'rh', 'ws', 'precip', 'rndays']], dataset['risk_band']

In [44]:
X.head()

   temp    rh    ws  precip  rndays
0   9.5  94.0   8.6   20.52       0
1   1.0  86.7  11.1    1.71       0
2  -2.0  74.4   0.0    0.00       1
3  13.2  97.0   3.7   16.80       0
4   2.0  93.2  13.0    3.80       0

## **Train test split**

In [48]:
# How does stratify help? Ensures the training and testing sets have the same proportion of classes as the orignal dataset. Very important when dealing with inbalanced datasets. 
# Like our processed dataset that has risk_band=no_risk inflated observations
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=34, stratify=y)
X_train

         temp    rh    ws  precip  rndays
2467872   0.4  42.0   7.1    0.00       4
2564958 -22.8  50.9   1.9    0.01       2
1501852  10.7  85.0  38.2    2.10       0
1709654  26.7  46.9  14.8    0.00      16
41571    12.6  75.0   0.0    1.02       0
...       ...   ...   ...     ...     ...
1289038  24.0  59.0  20.0    0.00       6
500886    9.4  50.0  15.2    6.40       0
2770420  -0.7  79.0   0.2    2.40       0
1018407  29.0  51.5   7.4    2.79       0
2469553   1.7  71.0   8.4    0.00       2

[2213460 rows x 5 columns]

## **Feature Scaling**

### Since LDA/QDA/KNN and classification techniques of the like are distance/variance sensitive therefore feature scaling is important. 
### Not important for logistic regression since feature values are always 0/1.

In [ ]:
scaler = StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_train)

array([[-7.18805659e-01, -8.88753492e-01, -7.29129644e-01,
        -5.39662160e-02,  7.24810251e-02],
       [-2.41547410e+00, -4.73439958e-01, -1.26694822e+00,
        -5.37040715e-02, -1.51732489e-01],
       [ 3.44566219e-02,  1.11781752e+00,  2.48743913e+00,
         1.08412505e-03, -3.75946003e-01],
       ...,
       [-7.99251145e-01,  8.37830865e-01, -1.44277352e+00,
         8.94845948e-03, -3.75946003e-01],
       [ 1.37277698e+00, -4.45441293e-01, -6.98101649e-01,
         1.91720942e-02, -3.75946003e-01],
       [-6.23733720e-01,  4.64515328e-01, -5.94675001e-01,
        -5.39662160e-02, -1.51732489e-01]], shape=(2213460, 5))

### **Fitting Logistic Regression**

In [ ]:
LogisticRegression(multi_class='multinomial', )